server:
  port: 8888
spring:
  application:
    name: avila-config-server
#  profiles:
#    active:
#    - native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fagneravila/avila-config-server
          # username:
          # password:
          default-label: main
          search-paths:
            - 'greeting-service*'

